---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      api.service.kubernetes.io/path: /services/helloservice/sayHello/
      fabric8.io/git-commit: 82a9a167a0a5a4ac4ae91d867124cca011a49cd2
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      app: spring-boot-cxf-jaxrs
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: io.fabric8.quickstarts.cxf.jaxrs
    name: spring-boot-cxf-jaxrs
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-boot-cxf-jaxrs
      provider: fabric8
      group: io.fabric8.quickstarts.cxf.jaxrs
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 82a9a167a0a5a4ac4ae91d867124cca011a49cd2
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=spring-boot-cxf-jaxrs&var-version=1.0-SNAPSHOT
    labels:
      app: spring-boot-cxf-jaxrs
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: io.fabric8.quickstarts.cxf.jaxrs
    name: spring-boot-cxf-jaxrs
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: spring-boot-cxf-jaxrs
      provider: fabric8
      group: io.fabric8.quickstarts.cxf.jaxrs
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 82a9a167a0a5a4ac4ae91d867124cca011a49cd2
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=spring-boot-cxf-jaxrs&var-version=1.0-SNAPSHOT
        labels:
          app: spring-boot-cxf-jaxrs
          provider: fabric8
          version: 1.0-SNAPSHOT
          group: io.fabric8.quickstarts.cxf.jaxrs
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":1}}}'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: spring-boot-cxf-jaxrs:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
              memory: 256Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: spring-boot-cxf-jaxrs:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      api.service.kubernetes.io/path: /services/helloservice/sayHello/
    labels:
      expose: "true"
      app: spring-boot-cxf-jaxrs
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: io.fabric8.quickstarts.cxf.jaxrs
    name: spring-boot-cxf-jaxrs
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: spring-boot-cxf-jaxrs
